FROM node:22

WORKDIR /usr/src/app

# Copiar apenas arquivos de dependência
COPY package*.json package-lock.json ./
RUN yarn install

# Copiar todo o restante do código
COPY . .

# Expor a porta padrão do Next.js
EXPOSE 3000

# Inicia no modo desenvolvimento
CMD ["yarn", "dev"]
