services:
  postgres:
    image: postgres
    container_name: todo-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"

  todo-api:
    container_name: todo-api
    build:
      context: ./api
      dockerfile: Dockerfile.production
    ports:
      - "${API_PORT}:3001"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_DATABASE: ${POSTGRES_DB}
    depends_on:
      - postgres

  todo-frontend:
    container_name: todo-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.production
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    ports:
      - "3000:3000"
    depends_on:
      - todo-api
